package com.grim3212.mc.pack.industry.init;

import com.grim3212.mc.pack.GrimPack;
import com.grim3212.mc.pack.decor.GrimDecor;
import com.grim3212.mc.pack.industry.GrimIndustry;

public class IndustryNames {

	// Blocks
	public static final String TOGGLE_RACK = GrimPack.modID + ":" + GrimIndustry.partId + "/toggle_rack";
	public static final String IRON_WORKBENCH = GrimPack.modID + ":" + GrimIndustry.partId + "/iron_workbench";
	public static final String DIAMOND_WORKBENCH = GrimPack.modID + ":" + GrimIndustry.partId + "/diamond_workbench";
	public static final String ICE_MAKER = GrimPack.modID + ":" + GrimIndustry.partId + "/ice_maker";
	public static final String ELEMENTAL_FIRE = GrimPack.modID + ":" + GrimIndustry.partId + "/elemental_fire";
	public static final String ELEMENTAL_WATER = GrimPack.modID + ":" + GrimIndustry.partId + "/elemental_water";
	public static final String ELEMENTAL_LAVA = GrimPack.modID + ":" + GrimIndustry.partId + "/elemental_lava";
	public static final String SPIKE = GrimPack.modID + ":" + GrimIndustry.partId + "/spike";
	public static final String WOODEN_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/wooden_sensor";
	public static final String STONE_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/stone_sensor";
	public static final String IRON_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/iron_sensor";
	public static final String NETHERRACK_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/netherrack_sensor";
	public static final String ATTRACTOR = GrimPack.modID + ":" + GrimIndustry.partId + "/attractor";
	public static final String REPULSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/repulsor";
	public static final String GRAVITOR = GrimPack.modID + ":" + GrimIndustry.partId + "/gravitor";
	public static final String DIRECTION_ATTRACTOR = GrimPack.modID + ":" + GrimIndustry.partId + "/direction_attractor";
	public static final String DIRECTION_REPULSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/direction_repulsor";
	public static final String DIRECTION_GRAVITOR = GrimPack.modID + ":" + GrimIndustry.partId + "/direction_gravitor";
	public static final String REACTOR = GrimPack.modID + ":" + GrimIndustry.partId + "/reactor";
	public static final String BOMB_SHELL = GrimPack.modID + ":" + GrimIndustry.partId + "/bomb_shell";
	public static final String C4 = GrimPack.modID + ":" + GrimIndustry.partId + "/c4";
	public static final String NUCLEAR_BOMB = GrimPack.modID + ":" + GrimIndustry.partId + "/nuclear_bomb";
	public static final String URANIUM_ORE = GrimPack.modID + ":" + GrimIndustry.partId + "/uranium_ore";
	public static final String CASTLE_GATE = GrimPack.modID + ":" + GrimIndustry.partId + "/castle_gate";
	public static final String GARAGE = GrimPack.modID + ":" + GrimIndustry.partId + "/garage";
	public static final String HALOGEN_LIGHT = GrimPack.modID + ":" + GrimIndustry.partId + "/halogen_light";
	public static final String HALOGEN_TORCH = GrimPack.modID + ":" + GrimIndustry.partId + "/halogen_torch";
	public static final String SIDEWALK = GrimPack.modID + ":" + GrimIndustry.partId + "/sidewalk";
	public static final String RWAY = GrimPack.modID + ":" + GrimIndustry.partId + "/rway";
	public static final String RWAY_LIGHT_ON = GrimPack.modID + ":" + GrimIndustry.partId + "/rway_light_on";
	public static final String RWAY_LIGHT_OFF = GrimPack.modID + ":" + GrimIndustry.partId + "/rway_light_off";
	public static final String RWAY_MANHOLE = GrimPack.modID + ":" + GrimIndustry.partId + "/rway_manhole";
	public static final String DOOR_CHAIN = GrimPack.modID + ":" + GrimIndustry.partId + "/door_chain";
	public static final String DOOR_GLASS = GrimPack.modID + ":" + GrimIndustry.partId + "/door_glass";
	public static final String DOOR_STEEL = GrimPack.modID + ":" + GrimIndustry.partId + "/door_steel";
	public static final String CONCRETE = GrimPack.modID + ":" + GrimIndustry.partId + "/concrete";
	public static final String MODERN_TILE = GrimPack.modID + ":" + GrimIndustry.partId + "/modern_tile";
	public static final String TEMPERED_GLASS = GrimPack.modID + ":" + GrimIndustry.partId + "/tempered_glass";
	public static final String HORIZONTAL_SIDING = GrimPack.modID + ":" + GrimIndustry.partId + "/horizontal_siding";
	public static final String VERTICAL_SIDING = GrimPack.modID + ":" + GrimIndustry.partId + "/vertical_siding";
	public static final String FOUNTAIN = GrimPack.modID + ":" + GrimIndustry.partId + "/fountain";
	public static final String CAMO_PLATE = GrimPack.modID + ":" + GrimIndustry.partId + "/camo_plate";
	public static final String CHAIN_FENCE = GrimPack.modID + ":" + GrimIndustry.partId + "/chain_fence";
	public static final String ALUMINUM_LADDER = GrimPack.modID + ":" + GrimIndustry.partId + "/aluminum_ladder";
	public static final String OIL_ORE = GrimPack.modID + ":" + GrimIndustry.partId + "/oil_ore";
	public static final String DERRICK = GrimPack.modID + ":" + GrimIndustry.partId + "/derrick";
	public static final String MODERN_FURNACE = GrimPack.modID + ":" + GrimIndustry.partId + "/modern_furnace";
	public static final String STEEL_PIPE = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_pipe";
	public static final String REFINERY = GrimPack.modID + ":" + GrimIndustry.partId + "/refinery";
	public static final String STEEL_FRAME = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_frame";
	public static final String FUEL_TANK = GrimPack.modID + ":" + GrimIndustry.partId + "/fuel_tank";
	public static final String FAN = GrimPack.modID + ":" + GrimIndustry.partId + "/fan";
	public static final String SPECIFIC_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/sepcific_sensor";
	public static final String UPGRADED_SPECIFIC_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/upgraded_specific_sensor";
	public static final String ARROW_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/arrow_sensor";
	public static final String METAL_MESH = GrimPack.modID + ":" + GrimIndustry.partId + "/metal_mesh";
	public static final String FIRE_SENSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/fire_sensor";
	public static final String CONVEYOR_BELT = GrimPack.modID + ":" + GrimIndustry.partId + "/conveyor_belt";
	public static final String DRILL = GrimPack.modID + ":" + GrimIndustry.partId + "/drill";
	public static final String DRILL_HEAD = GrimPack.modID + ":" + GrimIndustry.partId + "/drill_head";
	public static final String LOCKSMITH_WORKBENCH = GrimPack.modID + ":" + GrimIndustry.partId + "/locksmith_workbench";
	public static final String WOOD_CABINET = GrimPack.modID + ":" + GrimIndustry.partId + "/wood_cabinet";
	public static final String GLASS_CABINET = GrimPack.modID + ":" + GrimIndustry.partId + "/glass_cabinet";
	public static final String WAREHOUSE_CRATE = GrimPack.modID + ":" + GrimIndustry.partId + "/warehouse_crate";
	public static final String OBSIDIAN_SAFE = GrimPack.modID + ":" + GrimIndustry.partId + "/obsidian_safe";
	public static final String GOLD_SAFE = GrimPack.modID + ":" + GrimIndustry.partId + "/gold_safe";
	public static final String LOCKER = GrimPack.modID + ":" + GrimIndustry.partId + "/locker";
	public static final String ITEM_TOWER = GrimPack.modID + ":" + GrimIndustry.partId + "/item_tower";
	public static final String TANK = GrimPack.modID + ":" + GrimIndustry.partId + "/tank";
	public static final String SHAPED_CHARGE = GrimPack.modID + ":" + GrimIndustry.partId + "/shaped_charge";
	public static final String FLIP_FLOP_TORCH = GrimPack.modID + ":" + GrimIndustry.partId + "/flip_flop_torch";
	public static final String GLOWSTONE_TORCH = GrimPack.modID + ":" + GrimIndustry.partId + "/glowstone_torch";
	public static final String CHUNK_LOADER = GrimPack.modID + ":" + GrimIndustry.partId + "/chunk_loader";
	public static final String BRIDGE_CONTROL = GrimPack.modID + ":" + GrimIndustry.partId + "/bridge_control";
	public static final String BRIDGE = GrimPack.modID + ":" + GrimIndustry.partId + "/bridge";

	// Items
	public static final String GRAVITY_BOOTS = GrimPack.modID + ":" + GrimIndustry.partId + "/gravity_boots";
	public static final String URANIUM_INGOT = GrimPack.modID + ":" + GrimIndustry.partId + "/uranium_ingot";
	public static final String REFINED_URANIUM = GrimPack.modID + ":" + GrimIndustry.partId + "/refined_uranium";
	public static final String PLUTONIUM_INGOT = GrimPack.modID + ":" + GrimIndustry.partId + "/plutonium_ingot";
	public static final String REFINED_PLUTONIUM = GrimPack.modID + ":" + GrimIndustry.partId + "/refined_plutonium";
	public static final String REACTOR_CORE = GrimPack.modID + ":" + GrimIndustry.partId + "/reactor_care";
	public static final String REACTOR_CORE_CASE = GrimPack.modID + ":" + GrimIndustry.partId + "/reactor_core_case";
	public static final String IRON_PARTS = GrimPack.modID + ":" + GrimIndustry.partId + "/iron_parts";
	public static final String LOW_GRAVITY_CONTROLLER = GrimPack.modID + ":" + GrimIndustry.partId + "/low_gravity_controller";
	public static final String GRAVITY_CONTROLLER = GrimPack.modID + ":" + GrimIndustry.partId + "/gravity_controller";
	public static final String MOB_REPULSOR = GrimPack.modID + ":" + GrimIndustry.partId + "/mob_replusor";
	public static final String ANTI_RADIATION_HELMET = GrimPack.modID + ":" + GrimIndustry.partId + "/anti_radiation_helmet";
	public static final String ANTI_RADIATION_CHEST = GrimPack.modID + ":" + GrimIndustry.partId + "/anti_radiation_chest";
	public static final String ANTI_RADIATION_LEGS = GrimPack.modID + ":" + GrimIndustry.partId + "/anti_radiation_legs";
	public static final String ANTI_RADIATION_BOOTS = GrimPack.modID + ":" + GrimIndustry.partId + "/anti_radiation_boots";
	public static final String GATE_GRATING = GrimPack.modID + ":" + GrimIndustry.partId + "/gate_grating";
	public static final String GATE_TRUMPET = GrimPack.modID + ":" + GrimIndustry.partId + "/gate_trumpet";
	public static final String GARAGE_PANEL = GrimPack.modID + ":" + GrimIndustry.partId + "/garage_panel";
	public static final String GARAGE_REMOTE = GrimPack.modID + ":" + GrimIndustry.partId + "/garage_remote";
	public static final String PAINT_ROLLER = GrimPack.modID + ":" + GrimIndustry.partId + "/paint_roller";
	public static final String TARBALL = GrimPack.modID + ":" + GrimIndustry.partId + "/tarball";
	public static final String ASPHALT = GrimPack.modID + ":" + GrimIndustry.partId + "/asphalt";
	public static final String PAINT_ROLLER_WHITE = GrimPack.modID + ":" + GrimIndustry.partId + "/paint_roller_white";
	public static final String PAINT_ROLLER_RED = GrimPack.modID + ":" + GrimIndustry.partId + "/paint_roller_red";
	public static final String PAINT_ROLLER_GREEN = GrimPack.modID + ":" + GrimIndustry.partId + "/paint_roller_green";
	public static final String PAINT_ROLLER_BLUE = GrimPack.modID + ":" + GrimIndustry.partId + "/paint_roller_blue";
	public static final String COAL_IRON_INGOT = GrimPack.modID + ":" + GrimIndustry.partId + "/coal_iron_ingot";
	public static final String CRUDE_OIL = GrimPack.modID + ":" + GrimIndustry.partId + "/crude_oil";
	public static final String FUEL = GrimPack.modID + ":" + GrimIndustry.partId + "/fuel";
	public static final String OILY_CHUNK = GrimPack.modID + ":" + GrimIndustry.partId + "/oily_chunk";
	public static final String STEEL_AXE = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_axe";
	public static final String STEEL_HOE = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_hoe";
	public static final String STEEL_PICKAXE = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_pickaxe";
	public static final String STEEL_SHOVEL = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_shovel";
	public static final String STEEL_SWORD = GrimPack.modID + ":" + GrimIndustry.partId + "/steel_sword";
	public static final String SUPER_CRUDE_OIL = GrimPack.modID + ":" + GrimIndustry.partId + "/super_crude_oil";
	public static final String DRILL_HEAD_ITEM = GrimPack.modID + ":" + GrimIndustry.partId + "/drill_head_item";
	public static final String EXTRUDER = GrimPack.modID + ":" + GrimIndustry.partId + "/extruder";
	public static final String PORTABLE_DIAMOND_WORKBENCH = GrimPack.modID + ":" + GrimIndustry.partId + "/portable_diamond_workbench";
	public static final String PORTABLE_IRON_WORKBENCH = GrimPack.modID + ":" + GrimIndustry.partId + "/portable_iron_workbench";
	public static final String POSITION_FINDER = GrimPack.modID + ":" + GrimIndustry.partId + "/position_finder";
	public static final String LOCKSMITH_LOCK = GrimPack.modID + ":" + GrimIndustry.partId + "/locksmith_lock";
	public static final String LOCKSMITH_KEY = GrimPack.modID + ":" + GrimIndustry.partId + "/locksmith_key";

	// Sounds
	public static final String SOUND_SPIKE_DEPLOY = GrimPack.modID + ":" + GrimDecor.partId + "/spike_deploy";
	public static final String SOUND_SPIKE_CLOSE = GrimPack.modID + ":" + GrimDecor.partId + "/spike_close";
}
